RISC-V: Some fixes for riscv port
RISC-V: Fix the undeclared ‘EM_RISCV’ build failure
===================================================

Use local `elf.h` instead of `linux/elf.h` to fix this build error:

```
kexec/arch/riscv/crashdump-riscv.c:17:13: error: ‘EM_RISCV’ undeclared here (not in a function); did you mean ‘EM_CRIS’?
  .machine = EM_RISCV,
             ^~~~~~~~
             EM_CRIS
```

RISC-V: Correct the usage of command line option
================================================

RISC-V process OPT_CMDLINE with the "command-line" partten,
but the riscv_opts_usage shows the "cmdline" option.
So correct the usage's output.

RISC-V: Use linux,usable-memory-range for crash kernel
======================================================

Now we use "memeory::linux,usable-memory" to indicate the available
memory for the crash kernel.

While booting with UEFI, the crash kernel would use efi.memmap to
re-populate memblock and then first kernel's memory would be corrputed.
Consequently, the /proc/vmcore file failed to create in my local test.

And according to "chosen" dtschema [1], the available memory for the
crash kernel should be held via "chosen::linux,usable-memory-range"
property which will re-cap memblock even after UEFI's re-population.

[1]: https://github.com/devicetree-org/dt-schema/blob/main/dtschema/schemas/chosen.yaml

RISC-V: Get memory ranges from iomem
====================================

When booting with UEFI, Linux marks the Runtime Code/Data memory
as no-map and then exports it to "Reserved" iomem_resource.

Kexc-tools uses dtb_get_memory_ranges() function to get memory ranges
via parsing dtb, but it can't see the Reserved EFI Runtime memory.
That would corrupt EFI Runtime memory and fail the kexeced kernel to
deal EFI stuff.

In my test, the kexeced kernel warned "efi: System table signature incorrect!"
and then paniced at efi_call_rts() due to the null efi.runtime.

So we should use /proc/iomem to get memory ranges.

Signed-off-by: Song Shuai <songshuaishuai@tinylab.org>